env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      
language: node_js
node_js:
  - "6"

services:
  - mongodb


before_install:
   - npm install -g gulp-cli
   - npm install -g typescript@latest
   - npm install

script:
  - gulp
  - npm test
